N_E: 4000
N_I: 1000
Q: 20
focus_count: 1
V_th: 1.0
g: 1.2
p0_ee: 0.2 #0.1
p0_ie: 0.5 #0.2
p0_ei: 0.5 #0.2
p0_ii: 0.5 #0.2
tau_e: 10.0
tau_i: 5.0
R_Eplus: null
R_j: 0.75
kappa: 1.0
connection_type: poisson
m_X: 0.03
collapse_types: true
initial_activity:
  mode: poisson
  excitatory: null
  inhibitory: null
binary:
  warmup_steps: 60000
  simulation_steps: 3000000
  sample_interval: 10
  batch_size: 10
  state_chunk_size: 0
  population_rate_init: 0.1
  seed: null
  output_name: activity_trace
  plot_activity: false
  log_step_states: true
  log_decimate_factor: 10
  log_decimate_zero_phase: true
  log_decimate_ftype: iir
  update_queue:
    enabled: true
    chunk_size: 5000
    excitatory_repeat: 1
    inhibitory_repeat: 2
